// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.Data;

namespace Website.Migrations
{
    [DbContext(typeof(LineWebhookContext))]
    [Migration("20200517095633_Add_YearlyTradingInformation")]
    partial class Add_YearlyTradingInformation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Domain.Entities.TWSE_Stock.DividendDistribution", b =>
                {
                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<float>("CashDividendsFromLegalReserveAndCapitalSurplus")
                        .HasColumnType("real");

                    b.Property<float>("CashDividendsToBeDistributedFromRetainedEarnings")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("SharesDistributedFromEarnings")
                        .HasColumnType("real");

                    b.Property<float>("SharesDistributedFromLegalReserveAndCapitalSurplus")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Year", "StockCode");

                    b.ToTable("DividendDistributions");
                });

            modelBuilder.Entity("Core.Domain.Entities.TWSE_Stock.Exchange.DailyQuote", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<float>("Change")
                        .HasColumnType("real");

                    b.Property<float>("ClosingPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<float>("HighestPrice")
                        .HasColumnType("real");

                    b.Property<float>("LastBestAskPrice")
                        .HasColumnType("real");

                    b.Property<int>("LastBestAskVolume")
                        .HasColumnType("int");

                    b.Property<float>("LastBestBidPrice")
                        .HasColumnType("real");

                    b.Property<int>("LastBestBidVolume")
                        .HasColumnType("int");

                    b.Property<float>("LowestPrice")
                        .HasColumnType("real");

                    b.Property<float>("OpeningPrice")
                        .HasColumnType("real");

                    b.Property<float>("PriceEarningRatio")
                        .HasColumnType("real");

                    b.Property<long>("TradeValue")
                        .HasColumnType("bigint");

                    b.Property<int>("TradeVolume")
                        .HasColumnType("int");

                    b.Property<int>("Transaction")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Date", "StockCode");

                    b.ToTable("DailyQuotes");
                });

            modelBuilder.Entity("Core.Domain.Entities.TWSE_Stock.Exchange.YearlyTradingInformation", b =>
                {
                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<float>("AverageClosingPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("HighestPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("HighestPriceDate")
                        .HasColumnType("date");

                    b.Property<float>("LowestPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("LowestPriceDate")
                        .HasColumnType("date");

                    b.Property<long>("TradeValue")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeVolume")
                        .HasColumnType("bigint");

                    b.Property<int>("Transaction")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Year", "StockCode");

                    b.ToTable("YearlyTradingInformations");
                });

            modelBuilder.Entity("Core.Domain.Entities.TWSE_Stock.StockValueEstimation", b =>
                {
                    b.Property<string>("StockCode")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<float>("CheapPriceByDividendsIn10Years")
                        .HasColumnType("real");

                    b.Property<float>("CheapPriceByDividendsIn5Years")
                        .HasColumnType("real");

                    b.Property<float>("CheapPriceByRecentDividends")
                        .HasColumnType("real");

                    b.Property<float>("CheapPriceByStockPriceOver10Years")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("DividendsIn10Years")
                        .HasColumnType("real");

                    b.Property<float>("DividendsIn5Years")
                        .HasColumnType("real");

                    b.Property<float>("ExpensivePriceByDividendsIn10Years")
                        .HasColumnType("real");

                    b.Property<float>("ExpensivePriceByDividendsIn5Years")
                        .HasColumnType("real");

                    b.Property<float>("ExpensivePriceByRecentDividends")
                        .HasColumnType("real");

                    b.Property<float>("ExpensivePriceByStockPriceOver10Years")
                        .HasColumnType("real");

                    b.Property<float>("ReasonablePriceByDividendsIn10Years")
                        .HasColumnType("real");

                    b.Property<float>("ReasonablePriceByDividendsIn5Years")
                        .HasColumnType("real");

                    b.Property<float>("ReasonablePriceByRecentDividends")
                        .HasColumnType("real");

                    b.Property<float>("ReasonablePriceByStockPriceOver10Years")
                        .HasColumnType("real");

                    b.Property<float>("RecentDividends")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StockCode");

                    b.ToTable("StockValueEstimations");
                });
#pragma warning restore 612, 618
        }
    }
}
