name: Build, Deploy and Notice

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPOSITORY: ${{ 'linewebhook' }}
  IMAGE_TAG: ${{ 'latest' }}
  LINE_NOTIFY: ${{ secrets.LINE_NOTIFY_BEARER_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_JACKY_CHAT_ID: ${{secrets.TELEGRAM_JACKY_CHAT_ID}}

#   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
#   RUN_REGION: us-west1
#   SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

jobs:
  push_image_to_docker_hub:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      #- name: Extract metadata (tags, labels) for Docker
      #  id: meta
      #  uses: docker/metadata-action@v4.3.0
      #  with:
      #    images: ${{ secrets.DOCKER_USERNAME }}/linewebhook
      - name: Build image
        run: docker build --tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG .

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG

      - name: Log in to GCP
        run: gcloud auth login --remote-bootstrap="https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=32555940559.apps.googleusercontent.com&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=tgIibU1T1ODuxAZIoCAqDiGiRIjvXM&access_type=offline&code_challenge=Kmdy1ClgSEhKEbf7gEs01KLruv4Qphg-h7Kd5eTz7QA&code_challenge_method=S256&token_usage=remote"

  deploy_to_cloud_run:
    name: Deploy to cloud run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: echo tags, labels
        run: |
          echo "DOCKER_USERNAME = $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG =="
          echo "DOCKER_HUB_REPOSITORY = $DOCKER_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG =="
      #       - name: Build Docker image
      #         run: |
      #           docker build . --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      #       - name: Setup gcloud CLI
      #         uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #         with:
      #           service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      #           service_account_key: ${{ secrets.GCP_SERVICE_APPLICATION_CREDENTIALS }}
      #           project_id: ${{ secrets.GCP_PROJECT_ID }}

      #       - name: Configure Docker to use Google Cloud Platform
      #         run: 'gcloud auth configure-docker --quiet'

      #       - name: Push image to Google Cloud Container Registry
      #         run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      #       - name: Deploy image to Cloud Run
      #         run: |-
      #           gcloud run deploy "$SERVICE_NAME" \
      #             --quiet \
      #             --region "$RUN_REGION" \
      #             --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
      #             --platform "managed" \
      #             --allow-unauthenticated

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y/%m/%d %H:%M')" >> $GITHUB_ENV

      - name: Set top commit message as env variable
        run: echo "TOP_COMMIT_MESSAGE=$(git log --pretty=format:"%s" -1)" >> $GITHUB_ENV

      #     - name: Build and deploy the Docker image
      #       run: |
      #         cd .
      #         docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      #         heroku container:push web -a $APP_NAME
      #         heroku container:release web -a $APP_NAME

      #- name: Line Notice
      #  run: |
      #    curl -H "Authorization: Bearer $LINE_NOTIFY" \
      #         -d "message=[$NOW] [${GITHUB_SHA::8}] $TOP_COMMIT_MESSAGE" \
      #         https://notify-api.line.me/api/notify
#          curl -X GET "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_JACKY_CHAT_ID&text=佈版完成 ($NOW) $TOP_COMMIT_MESSAGE"
#          curl -H "Authorization: Bearer $LINE_NOTIFY" -d "message=佈版完成 ($NOW) $TOP_COMMIT_MESSAGE" https://notify-api.line.me/api/notify
