name: Build, Deploy and Notice

on:
  push:
    branches:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'linewebhookapp' }}
  DOCKER_REPOSITORY: ${{ 'linewebhook' }}
  LINE_NOTIFY: ${{ secrets.LINE_NOTIFY_BEARER_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_JACKY_CHAT_ID: ${{secrets.TELEGRAM_JACKY_CHAT_ID}}

#   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
#   RUN_REGION: us-west1
#   SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: j10926jacky/linewebhook
      
      - name: echo tags, labels
        run: |
          echo "tags == ${{ steps.meta.outputs.tags }} =="
          echo "labels == ${{ steps.meta.outputs.labels }} =="
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  gcp-setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      #       - name: Build Docker image
      #         run: |
      #           docker build . --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      #       - name: Setup gcloud CLI
      #         uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #         with:
      #           service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      #           service_account_key: ${{ secrets.GCP_SERVICE_APPLICATION_CREDENTIALS }}
      #           project_id: ${{ secrets.GCP_PROJECT_ID }}

      #       - name: Configure Docker to use Google Cloud Platform
      #         run: 'gcloud auth configure-docker --quiet'

      #       - name: Push image to Google Cloud Container Registry
      #         run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      #       - name: Deploy image to Cloud Run
      #         run: |-
      #           gcloud run deploy "$SERVICE_NAME" \
      #             --quiet \
      #             --region "$RUN_REGION" \
      #             --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
      #             --platform "managed" \
      #             --allow-unauthenticated

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y/%m/%d %H:%M')" >> $GITHUB_ENV

      - name: Set top commit message as env variable
        run: echo "TOP_COMMIT_MESSAGE=$(git log --pretty=format:"%s" -1)" >> $GITHUB_ENV

      #     - name: Build and deploy the Docker image
      #       run: |
      #         cd .
      #         docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      #         heroku container:push web -a $APP_NAME
      #         heroku container:release web -a $APP_NAME

      #- name: Line Notice
      #  run: |
      #    curl -H "Authorization: Bearer $LINE_NOTIFY" \
      #         -d "message=[$NOW] [${GITHUB_SHA::8}] $TOP_COMMIT_MESSAGE" \
      #         https://notify-api.line.me/api/notify

#          curl -X GET "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_JACKY_CHAT_ID&text=佈版完成 ($NOW) $TOP_COMMIT_MESSAGE"
#          curl -H "Authorization: Bearer $LINE_NOTIFY" -d "message=佈版完成 ($NOW) $TOP_COMMIT_MESSAGE" https://notify-api.line.me/api/notify
