name: Build, Deploy and Notice

on:
  push:
    branches:
      - master

env:
  LINE_NOTIFY: ${{ secrets.LINE_NOTIFY_BEARER_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_JACKY_CHAT_ID: ${{secrets.TELEGRAM_JACKY_CHAT_ID}}
  IMAGE_TAG: latest

jobs:
  push_image_to_docker_hub:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ env.URL}}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build image
        run: docker build --tag ${{ env.DOCKER_USER}}/${{ env.REPOSITORY_NAME }}:$IMAGE_TAG.

      - name: Log in to Docker Hub
        run: docker login -u ${{ env.DOCKER_USER}} -p $DOCKER_PASSWORD

      - name: Push to Docker Hub
        run: docker push ${{ env.DOCKER_USER}}/${{ env.REPOSITORY_NAME }}:$IMAGE_TAG

      - name: Log in to gcloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to cloud run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.CLOUD_RUN_SERVICE }}
          image: docker.io/${{ env.DOCKER_USER}}/${{ env.DOCKER_REPOSITORY}}

      - name: Info
        run: gcloud info

      - name: echo tags, labels
        run: |
          echo "DOCKER_USER  = ${{ env.DOCKER_USER}}  =="
          echo "CLOUD_RUN_SERVICE = ${{ env.CLOUD_RUN_SERVICE }} =="
          echo "CLOUD_RUN_REGION = ${{ env.CLOUD_RUN_REGION }} =="

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
            --region=asia-east1 \
            --image=docker.io/${{ env.DOCKER_USERNAME }}/linewebhook \
            --platform=managed \
            --quiet \
            --port=80 \
            --allow-unauthenticated

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y/%m/%d %H:%M')" >> $GITHUB_ENV

      - name: Set top commit message as env variable
        run: echo "TOP_COMMIT_MESSAGE=$(git log --pretty=format:"%s" -1)" >> $GITHUB_ENV

      - name: Line Notice
        run: |
          curl -H "Authorization: Bearer $LINE_NOTIFY" \
            -d "message=[$NOW] [${GITHUB_SHA::8}] $TOP_COMMIT_MESSAGE" \
            https://notify-api.line.me/api/notify
          curl -X GET "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_JACKY_CHAT_ID&text=佈版完成 ($NOW) $TOP_COMMIT_MESSAGE"
