name: CI

on:
  push:
    branches:
    - master

env: 
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'linewebhookapp' }}
  LINE_NOTIFY: ${{ secrets.LINE_NOTIFY_BEARER_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_JACKY_CHAT_ID: ${{secrets.TELEGRAM_JACKY_CHAT_ID}} 
  
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-east1
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
  ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_APPLICATION_CREDENTIALS }}:  

jobs:
  gcp-setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup GCP Service Account
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Build and push image to Google Container Registry
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME

    - name: Deploy image to Cloud Run
      run: |-
        gcloud run deploy --image gcr.io/$PROJECT_ID/$SERVICE_NAME --platform managed
  build_linewebhook2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set current date as env variable
      run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"
    - name: Set top commit message as env variable
      run: echo "::set-env name=TOP_COMMIT_MESSAGE::$(git log --pretty=format:"%s" -1)"
    - name: Build and deploy the Docker image
      run: |
        cd .
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
        curl -X GET "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_JACKY_CHAT_ID&text=佈版完成 ($NOW) $TOP_COMMIT_MESSAGE"
        curl -H "Authorization: Bearer $LINE_NOTIFY" -d "message=佈版完成 ($NOW) $TOP_COMMIT_MESSAGE" https://notify-api.line.me/api/notify
        
